### ISSUE TITLE
Not sending server status

### ISSUE THREAD

**Issue by GKILLA1** [weleho/fivem-status-bot#3]
After setting up the config, the bot said to copy message link then put into config and restart script.
I have done all that as you should but the bot does not post anything in the discord after that.
i restarted the script/server after putting the message link in just in case but to no avail.

here is what the debug says 

[script:weleho_status] Updating Status Message [Date: 06/06/2021  |  Time: 04:16 AM]
[script:weleho_status] [DEBUG] err=	400
[script:weleho_status] [DEBUG] text=	nil

**Comment by weleho** [comment]
can you show your config, hide webhook

**Comment by GKILLA1** [comment]
sure 
![image](https://user-images.githubusercontent.com/76872252/120932276-0d712600-c6ed-11eb-8c7b-cde6772e02f1.png)

**Comment by weleho** [comment]
Make sure that JoinLink is URL, like: https://cfx.re/join/xp34mg
